const DEFAULT_LEFT = 600;
const DEFAULT_TOP = 300;
const DEFAULT_WIDTH = 680;
const DEFAULT_HEIGHT = 400;
const MIN_WIDTH = 300;
const MIN_HEIGHT = 160;
const DEFAULT_CORNER_RADIUS = 20;
const INTERACTIONS = {
  NONE: 0,
  MOVING: 1,
  RESIZE_TOP: 2,
  RESIZE_RIGHT: 3,
  RESIZE_BOTTOM: 4,
  RESIZE_LEFT: 5,
  RESIZE_TOP_LEFT: 6,
  RESIZE_TOP_RIGHT: 7,
  RESIZE_BOTTOM_RIGHT: 8,
  RESIZE_BOTTOM_LEFT: 9,
};

export {
  DEFAULT_TOP,
  DEFAULT_LEFT,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  MIN_WIDTH,
  MIN_HEIGHT,
  DEFAULT_CORNER_RADIUS,
  INTERACTIONS
};
