const DEFAULT_LEFT = 200;
const DEFAULT_TOP = 200;
const DEFAULT_WIDTH = 340;
const DEFAULT_HEIGHT = 200;
const DEFAULT_CORNER_RADIUS = 20;

export {
    DEFAULT_TOP,
    DEFAULT_LEFT,
    DEFAULT_WIDTH,
    DEFAULT_HEIGHT,
    DEFAULT_CORNER_RADIUS
}