const DEFAULT_LEFT = 600;
const DEFAULT_TOP = 300;
const DEFAULT_WIDTH = 340;
const DEFAULT_HEIGHT = 200;
const MIN_WIDTH = 300;
const MIN_HEIGHT = 160;
const DEFAULT_CORNER_RADIUS = 20;

export {
  DEFAULT_TOP,
  DEFAULT_LEFT,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  MIN_WIDTH,
  MIN_HEIGHT,
  DEFAULT_CORNER_RADIUS,
};
